### PR TITLE
Service properties modified

### PR DESCRIPTION
**Pull request by this-Aditya**
Fixes issue https://github.com/RADAR-base/radar-commons-android/issues/92

### CODE REVIEW

**Comment by this-Aditya** [comment]
Could you please take a look at this pull request?
@blootsvoets @afolarin @peyman-mohtashami

**Review by blootsvoets — COMMENTED** [review]
Nice update, LGTM. Could you please rebase with dev to get a clean commit?

**Comment by this-Aditya** [comment]
Sure.

**Comment by this-Aditya** [comment]
Here it is #417

**Pull request closed without merging**
