### PR TITLE
hash is created for Bluetooth device mac address

### PR DESCRIPTION
**Pull request by this-Aditya**
Fixes issue #253

### CODE REVIEW

**Comment by this-Aditya** [comment]
hello I am new to this project i made this pr, if there is some mistake please let me know. I have provided the parameter as context and "app" while creating the instance of HashGenerator .

**Comment by afolarin** [comment]
:+1:  @this-Aditya - I'll get @blootsvoets to review. 
This will also need changes to the https://github.com/RADAR-base/RADAR-Schemas/blob/master/commons/passive/phone/phone_bluetooth_devices.avsc but I guess we can get the changes in place here first.

**Comment by this-Aditya** [comment]
Okay, Does  it mean I need to add two more properties in fields for mac address and hash generated

**Review by blootsvoets — COMMENTED** [review]
This is a good first step. As Amos mentioned, to send this data a new schema is needed. The best would be that every bluetooth device would constitute one record. It would then be sent to a new data topic. Something like the following during initialization:
```kotlin
val bluetoothScannedTopic = createCache("android_phone_bluetooth_device_scanned", PhoneBluetoothDeviceScanned())
```
And when a device is actually found:
```kotlin
send(bluetoothScannedTopic, PhoneBluetoothDeviceScanned.Builder().apply {
  time = currentTime
  timeReceived = time
  macAddressHash = hash
}.build())
```
Then https://github.com/RADAR-base/RADAR-Schemas/blob/master/specifications/passive/android_phone-1.0.0.yml would need to be updated to match the new schema with the new topic.

**Comment by this-Aditya** [comment]
hello @blootsvoets. I am having difficulty in getting through https://github.com/RADAR-base/RADAR-Schemas/blob/master/specifications/passive/android_phone-1.0.0.yml in order to make this pull request. Currently I am only in the learning stage of android development and aware of basic things like networking, databases, coroutines, firebase etc. As I am having some difficulty can you please suggest me some domains which I need to learn and then contribute to this or can you please suggest me some android development related issues. Thanks :)

**Comment by this-Aditya** [comment]
Or do I need to go through complete codebase of radarbase and then contribute to this project. As of now I am just looking and these specific kotlin classes and then making changes to it.

**Comment by this-Aditya** [comment]
hey @blootsvoets  I made the changes as you said, please review it and tell me if there is any mistakes in these

**Pull request closed without merging**
