### PR TITLE
LocalBroadcastManager will broadcast the location change

### PR DESCRIPTION
**Pull request by this-Aditya**
* Added feature to broadcast location changes by `PhoneLocationManager`
 
{ LocalBroadcastManager Dependencies are added as it was not imported by default. }
 { Constant `DEVICE_LOCATION_CHANGE` is in the GooglePlaces Plugin. }

### CODE REVIEW

**Review by blootsvoets — COMMENTED** [review]
I see no problem with it, but what is the use case? If you want to reuse the value, then it makes sense to add a bundle with the corresponding location value.

**Comment by this-Aditya** [comment]
Hi, in the Google Places plugin, the `processPlacesData()` function sends data in two cases:
1. Every 600 seconds.
2. When the device's location changes.

The device's location change is broadcast from here. In this case, we don't want to reuse the value; we simply need to find the places info.

**Review by blootsvoets — APPROVED** [review]
Alright that makes sense. LGTM

**Comment by this-Aditya** [comment]
Thanks.

**Pull request merged**
