### PR TITLE
fun didreceiveTag() will now send the received tag data to platform

### PR DESCRIPTION
**Pull request by this-Aditya**
fixes issue https://github.com/RADAR-base/radar-commons-android/issues/295

### CODE REVIEW

**Review by yatharthranjan — APPROVED** [review]
LGTM

**Comment by yatharthranjan** [comment]
Hi @this-Aditya please change the base of this PR to `dev` branch

**Comment by this-Aditya** [comment]
@yatharthranjan done

**Comment by this-Aditya** [comment]
@yatharthranjan is there any way to fix ci failing. As I am not aware of it.

**Comment by yatharthranjan** [comment]
Looks like some deprecated api use in the ppg plugin. Perhaps @blootsvoets can comment.

**Comment by this-Aditya** [comment]
Hello, as topic ``android_empatica_e4_tag`` is not present  [here](https://github.com/RADAR-base/RADAR-Schemas/blob/master/specifications/passive/empatica_e4-1.1.0.yml). Do I need to add this too.

**Comment by this-Aditya** [comment]
Hi @yatharthranjan, it is passing the CI test now.

**Review by yatharthranjan — APPROVED** [review]
LGTM.

**Review by yatharthranjan — APPROVED** [review]
LGTM.

**Pull request merged**
