### PR TITLE
Updated icons to be displayed with plugins

### PR DESCRIPTION
**Pull request by this-Aditya**

### CODE REVIEW

**Review by yatharthranjan — COMMENTED** [review]
Looks good but please fix the CI first.

**Comment by yatharthranjan** [comment]
I also think would be nice to have different icons for different states (like disconnection state could show a RED icon with a slash or cross to signify the same, and collecting state could be blue while idle state could be gray).

**Comment by this-Aditya** [comment]
Thanks for the review. I'll update it accordingly.

**Comment by this-Aditya** [comment]
> I also think would be nice to have different icons for different states (like disconnection state could show a RED icon with a slash or cross to signify the same, and collecting state could be blue while idle state could be gray).

@yatharthranjan  Is this feature already implemented in the code? -> [updateSourceStatus()](https://github.com/RADAR-base/radar-prmt-android/blob/4b94b9d28a41e963eaa04ac1aa63cb795620f5cd/app/src/main/java/org/radarcns/detail/SourceRowView.kt#L149)

**Pull request closed without merging**
